### ISSUE TITLE
Support for Portable Python

### ISSUE THREAD

**Issue by arturluizbr** [crazy-max/nodejs-portable#10]
There is some node modules that requires python to install, so it would be nice to add this functionality.

**Comment by crazy-max** [comment]
I have started to implement a portable version of Python for the [Neard project](https://github.com/crazy-max/neard-tool-python).
I will check if it's possible to use the bundle.

**Comment by crazy-max** [comment]
You can now customize the Git and Python path with the configuration file nodejs-portable.conf (see README) in the latest release (2.1.2)
