### ISSUE TITLE
Implement Microsoft compiler

### ISSUE THREAD

**Issue by ghost** [crazy-max/nodejs-portable#18]
Thanks for doing this...
1. will we be moving to more recent versions of NodeJS or x64?
2. is there a way we can get support for modules, like jdbc, that require a Microsoft compiler? If i had access to a microsoft compiler I'd have admin access and wouldn't have to put nodejs on a portable drive!

**Comment by crazy-max** [comment]
Hi

I will implement the possibility to choose version and arch.
For Microsoft compiler i keep you in touch.
