### ISSUE TITLE
Rewrite In PowerShell

### ISSUE THREAD

**Issue by LogoiLab** [crazy-max/nodejs-portable#22]
the code can be simplified and less crufty if you rewrite it in powershell. If you need help let me know.

**All Hail PowerShell, BATCH is Dead**

**Comment by lashchev** [comment]
Actually with introduction of Bash subsystem to Windows 10 should we do it in Bash? I do most of my scripts in Bash now so they run on Windows and Linux

**Comment by LogoiLab** [comment]
Bash in windows is handled by KSH Or the kornshell it has sketchy suppor at best for even the most basic bash tools

**Comment by crazy-max** [comment]
A BIG rewrite in Golang has be done and will be available asap
