### ISSUE TITLE
"\Git\cmd" syntax error on launch

### ISSUE THREAD

**Issue by KolyaKorruptis** [crazy-max/nodejs-portable#23]
Installation went fine but I received a syntax error on trying to launch nodejs:

> "\Git\cmd" kann syntaktisch an dieser Stelle nicht verarbeitet werden.

**Comment by crazy-max** [comment]
Hi,

GIT seems not to be set as env var on your system but it's not a real issue for you.
Juste have to deal with this behavior in the script.

**Comment by crazy-max** [comment]
Solved in 1.13
