### ISSUE TITLE
Super quick start example

### ISSUE THREAD

**Issue by maphew** [crazy-max/nodejs-portable#24]
Quick batch file to fetch current version of Nodejs-portable and run it. 

```
mkdir new-node
pushd new-node
call Bitsadmin /transfer "default"  ^
   https://raw.githubusercontent.com/crazy-max/nodejs-portable/master/nodejs-portable.bat ^
   %cd%\new-node\nodejs-portable.bat

call nodejs-portable.bat
```

Windows XP through Win7. Win 8 and newer should use Powershell (http://superuser.com/questions/129269/download-a-file-via-http-from-a-script-in-windows), though our Server 2012 still has it and it works.

**Comment by crazy-max** [comment]
Hi,

What is the purpose of your issue ?

**Comment by maphew** [comment]
Meant as a suggested possible inclusion to the instructions or examples.
Something that can be scripted and get a person up and running quickly. An
alternative to mousing and clicking and finding a place to save.

I guess I didn't introduce or frame it that way, sorry about that.

**Comment by crazy-max** [comment]
Ok but it would be better to rewrite the script in pure PowerShell.
If you have time you can create a PR :)

**Comment by maphew** [comment]
Yeah, PowerShell would be good, however it's not universally available,
though the number of machines without it is steadily decreasing.

**Comment by crazy-max** [comment]
Of course ;)
