### ISSUE TITLE
work directory not opened

### ISSUE THREAD

**Issue by semecan** [crazy-max/nodejs-portable#25]
When I added nodejs-portable to my start menu, launching it from there did not put me in the "work"-folder, but in the location of the cmd.exe.
I fixed the issue by putting 
pushd "%~dp0"
right after the "Batch vars" SET-Block.

**Comment by crazy-max** [comment]
@semecan, thanks for your feedback, this will be added asap.

**Comment by crazy-max** [comment]
Solved in 1.13
