### ISSUE TITLE
crash when invalid characters in PATH variable

### ISSUE THREAD

**Issue by semecan** [crazy-max/nodejs-portable#26]
Some programs (e.g. some AMD drivers) put brackets or other symbols in the PATH variable.
In line 171 the path variable gets interpreted and if it contains batch syntax symbols, nodejs-portable crashes.
I circumvented this by putting the value of that SET command in apostrophes:
SET "PATH=%PATH%;%GIT%cmd".

**Comment by crazy-max** [comment]
Hi @semecan, thanks for your feedback this will be solved in the next release!

**Comment by crazy-max** [comment]
Solved in 1.13
