### ISSUE TITLE
2 problems and 2 questions

### ISSUE THREAD

**Issue by xiazeyu** [crazy-max/nodejs-portable#29]
### 1. Error on compiling the program using go.
```
D:\git\nodejs-portable>go get github.com/crazy-max/nodejs-portable/app/util
# github.com/crazy-max/nodejs-portable/app/util
C:\Users\xiaze\go\src\github.com\crazy-max\nodejs-portable\app\util\util.go:26:29: not enough arguments in call to grab.NewRequest
        have (string)
        want (string, string)
C:\Users\xiaze\go\src\github.com\crazy-max\nodejs-portable\app\util\util.go:32:30: grab.DefaultClient.DoAsync undefined (type *grab.Client has no field or method DoAsync)
```
  
  have a check, plz. To fix it I have temporarily deleted the whole downloading function, to make it work.

### 2. Lack of NODE_PATH environment

Because lack of NODE_PATH, some of the plugins cannot work properly. So I wrote a new code in **main.go funciton shell()**

    // NEW!!! SET NODE_PATH=%nodejsPath%\node_modules
	util.Print("SETTING NODE_PATH... ")
	if err := os.Setenv("NODE_PATH",  pathu.CurrentPath + "\\node_modules"); err != nil {
		util.PrintError(err)
	}
	util.PrintOk()

Hope you will add it in your application.

### 3. Thoughts about the Git Path.

Because the program is designed for portable use, the git may just **in the other path** in a USB drive, and the path of git is **not added in the PATH**. so, I recommend to let the user set the path manually, or add an optional git folder in the direction of the Portable Node.js. That will be more useful for USB device.

### 4. About compile

What command or how you used to compile the project?

I just use 
```bash
go get (all packages)
go build main.go
```
but it **don't have an icon, and it is very large than yours**, even if I deleted the whole download() funciton.

Please let me know these if you can, thank you.

Here's my forked repo, have a look if you want.
https://github.com/xiazeyu/nodejs-portable

**Comment by crazy-max** [comment]
Hi @xiazeyu,

1. I will add a "building" chapter in the README.md
2. Will be added in the next release
3. A configuration will be added to add a custom Git path
4. Same as 1.

**Comment by xiazeyu** [comment]
Thank you for your great work.

I found another problem, but **not confirmed**.
like the command: set path=I:\_apps\node\node_modules\npm;%path%
add node\node_modules\npm to the head of PATH **may** do help to

npm ERR! code EPERM
npm ERR! errno -4048

according to https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows
https://github.com/npm/npm/issues/9696

After I tried at my local version, I will tell the result.

**Comment by crazy-max** [comment]
Thanks for your contrib, I will investigate on this

**Comment by xiazeyu** [comment]
It seemed that I only need execute:
npm cache verify

but I add npm folder in case of other problems.
I may do some deeper research if I have time.

**Comment by crazy-max** [comment]
You can now customize the Git and Python path with the configuration file nodejs-portable.conf (see README) in the latest release (2.1.2)

For the other problem :

```
npm ERR! code EPERM
npm ERR! errno -4048
```

Please open a new issue if you confirm that.

**Comment by xiazeyu** [comment]
have a look into the Chinese document in 5e5b82aa12f5e5a176fac9d52eed8067b9740856
