### ISSUE TITLE
2 advice about custom path in setting

### ISSUE THREAD

**Issue by xiazeyu** [crazy-max/nodejs-portable#30]
## 1 none absolute path
First here's my path setting:
```
{
  "version": "2.1.2",
  "gitPath": "\\_apps\\PortableGit",
  "pythonPath": "\\_apps\\Python27"
}
```

And here's the actually path:
```
Your environment has been set up for using Node.js 8.4.0 (ia32) and npm.

I:\_apps\node\work>set path
Path=I:\_apps\node\node_modules\npm;I:\_apps\node;\_apps\Python27;\_apps\PortableGit\cmd;.........
```
Is there anyway to check or correct the relative path into absolute path?
Like add a drive letter before the custom path when detected.

so the actually path will like `I:\_apps\node` instead of `\_apps\node`

by the way, the 
```
npm ERR! code EPERM
npm ERR! errno -4048
```
problem is confirmed has nothing to do with your launcher, but is the npm's problem.
so it's *no use to add npm folder into path*
the advice of "add NODE_PATH" in #29 can already let npm found itself.
just use `npm cache clean --force` or `npm cache verify` can solve.

## 2 Advice about greater custom path
how about use
```
{
  "version": "2.1.2",
  "customPath": "\\_apps\\PortableGit;\\_apps\\Python27"
}
```
and add them into PATH(maybe cut of into groups first), so that the user will have more option if they want to add their own environment into PATH when use the launcher.
but it may become difficult when use none absolute path. I sew it in the Wordpress's code, found it good, but don't know if it can be realize using golang.

**Comment by crazy-max** [comment]
Yes I also thought to make an improvement by indicating relative paths. I'll work on it. The best way would be to indicate a relative path from the path where the `node-portable.exe` executable is located.

For example, if nodejs-portable is in `F:\apps\nodejs-portable` and the configuration file is like this :

```
{
  "version": "2.1.2",
  "gitPath": "../PortableGit",
  "pythonPath": "../Python27"
}
```

Then,

* `gitPath = F:\apps\PortableGit`
* `pythonPath = F:\apps\Python27`

I can add the new customPath element but I prefer to keep gitPath and pythonPath in order to check that their respective executables exist.

**Comment by xiazeyu** [comment]
that's now when I set `../PortableGit`
`Path=I:\_apps\node\node_modules\npm;I:\_apps\node;..\Python27;../PortableGit\cmd;`
and I mean you can remove `I:\_apps\node\node_modules\npm` from path

**Comment by crazy-max** [comment]
@xiazeyu New release 2.2.0 with :

* Resolve absolute paths in `customPaths`
* Merge `gitPath` and `pythonPath` in `customPaths`

> 💡 UPGRADE NOTE : `gitPath` and `pythonPath` have been removed from the config file and must be moved to `customPaths`
