### ISSUE TITLE
Open a work file directly

### ISSUE THREAD

**Issue by Snake4life** [crazy-max/nodejs-portable#34]
I set immediateMode to true and wanted to pass on "node app.js" to nodejs-portable.exe, but I cant get it to work

how can I manage to start an app directly with an batch file?

**Comment by crazy-max** [comment]
Hi, this is a new feature and it's definitely possible to implement it.

**Comment by xiazeyu** [comment]
It is possilbe to use `Args []` to receive varibles from cli, add I think a array of `afterStartupCommand`(sorry that I'm poor at name a feature) is also helpful.

**Comment by crazy-max** [comment]
Ok thanks for your input I will work on it this week!

**Comment by Snake4life** [comment]
thanks a lot, that will add a lot of value to this program

**Comment by crazy-max** [comment]
Implemented in the latest release. See https://github.com/crazy-max/nodejs-portable#command-line for more info.

**Comment by crazy-max** [comment]
@Snake4life In your case you will have to type `nodejs-portable app.js`
