### ISSUE TITLE
Setting custom workspace path

### ISSUE THREAD

**Issue by semecan** [crazy-max/nodejs-portable#35]
Could you implement the possibility of setting a custom workspace folder?
I personally would like to have my work folder somewhere else than inside the nodejs folder.

**Comment by crazy-max** [comment]
Hi @semecan, yes it's possible to implement this feature.

**Comment by semecan** [comment]
That's awessome to hear :)
Goes the same for the nodejs-directory?
If I could put nodejs in its own directory, I could just empty that folder and put in the new version when a nodejs update is released.

**Comment by crazy-max** [comment]
Hum yes i see what you mean. I can move node installation to an app folder for example.

Today we have :

![image](https://user-images.githubusercontent.com/1951866/34361913-f9d1efa2-ea6e-11e7-8438-9b4a6a49b8fd.png)

We can then move everything belong to node in an app subfolder :

![image](https://user-images.githubusercontent.com/1951866/34361941-2e0a7960-ea6f-11e7-9a0f-fd322926f541.png)

What do you think ?

**Comment by semecan** [comment]
That would be perfect!

**Comment by crazy-max** [comment]
Check the latest release ;)

**Comment by semecan** [comment]
Thanks alot, I will instantly try it out :)
