### ISSUE TITLE
Backslash path?

### ISSUE THREAD

**Issue by TokyoPiglet** [crazy-max/nodejs-portable#37]
Hello. When I run "npm run dev", I get an error:

..\app\node_modules\npm\npmrc: The system cannot find the path specified. 

Is this because npm is using a backslash path instead of forward slash? I'm doing it in a Git bash window. 

I also tested the command in a Windows cmd shell, but I got identical error.

**Comment by crazy-max** [comment]
@TokyoPiglet Can you post your `package.json` ?

**Comment by crazy-max** [comment]
Closed due to inactivity
