### ISSUE TITLE
batch file in user directory

### ISSUE THREAD

**Issue by semecan** [crazy-max/nodejs-portable#38]
I just noticed that when launching nodejs portable, a Folder named ".nodejs-portable" gets created in the user directory, containing a "launch.bat" file. This file persists even after exiting nodejs portable.
Is it possible to not create that folder + file in the user folder, but instead in the nodejs portable folder itself?

**Comment by crazy-max** [comment]
Hi @semecan,

Yes indeed, nodejs portable temporarly extract files in `%USERPROFILE%\.nodejs-portable` folder.
I will make some changes about that, thanks for your input.

**Comment by crazy-max** [comment]
Solved in 2.5.0
