### ISSUE TITLE
NPM Install E500

### ISSUE THREAD

**Issue by thereisnotime** [crazy-max/nodejs-portable#39]
When I try to install any package with npm install It gets stuck on:
**rollbackFailedOptional**

After a while it throws out this:

> D:\Git>npm install --save node-notifier
npm ERR! code E500
npm ERR! 500 Internal Server Error: node-notifier@latest
npm ERR! A complete log of this run can be found in:
npm ERR!     D:\Compilers\Nodejs\cache\_logs\2018-06-22T03_06_25_231Z-debug.log

Here is the current nodejs-portable.conf:

> {
  "version": "2.4.0",
  "immediateMode": false,
  "workPath": "./work",
  "customPaths": [
    "C:/Program Files/Git/cmd",
    "D:/Compilers/Nodejs/app",
    "D:/Compilers/Nodejs/app/node_modules/npm/bin"
  ]
}

Here is a cat of 2018-06-22T03_06_25_231Z-debug.log:

> 0 info it worked if it ends with ok
> 1 verbose cli [ 'D:\\Compilers\\Nodejs\\app\\node.exe',
> 1 verbose cli   'D:\\Compilers\\Nodejs\\app\\node_modules\\npm\\bin\\npm-cli.js',
> 1 verbose cli   'install',
> 1 verbose cli   '--save',
> 1 verbose cli   'node-notifier' ]
> 2 info using npm@6.1.0
> 3 info using node@v10.5.0
> 4 verbose npm-session a2702e4bdff176b0
> 5 silly install loadCurrentTree
> 6 silly install readLocalPackageData
> 7 http fetch GET 500 https://registry.npmjs.org/node-notifier 70915ms attempt #3
> 8 silly fetchPackageMetaData error for node-notifier@latest 500 Internal Server Error: node-notifier@latest
> 9 timing stage:rollbackFailedOptional Completed in 0ms
> 10 timing stage:runTopLevelLifecycles Completed in 71133ms
> 11 verbose stack Error: 500 Internal Server Error: node-notifier@latest
> 11 verbose stack     at fetch.then.res (D:\Compilers\Nodejs\app\node_modules\npm\node_modules\pacote\lib\fetchers\registry\fetch.js:42:19)
> 11 verbose stack     at tryCatcher (D:\Compilers\Nodejs\app\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
> 11 verbose stack     at Promise._settlePromiseFromHandler (D:\Compilers\Nodejs\app\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
> 11 verbose stack     at Promise._settlePromise (D:\Compilers\Nodejs\app\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
> 11 verbose stack     at Promise._settlePromise0 (D:\Compilers\Nodejs\app\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
> 11 verbose stack     at Promise._settlePromises (D:\Compilers\Nodejs\app\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
> 11 verbose stack     at Async._drainQueue (D:\Compilers\Nodejs\app\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
> 11 verbose stack     at Async._drainQueues (D:\Compilers\Nodejs\app\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
> 11 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (D:\Compilers\Nodejs\app\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
> 11 verbose stack     at runCallback (timers.js:696:18)
> 11 verbose stack     at tryOnImmediate (timers.js:667:5)
> 11 verbose stack     at processImmediate (timers.js:649:5)
> 12 verbose cwd D:\Git
> 13 verbose Windows_NT 10.0.17134
> 14 verbose argv "D:\\Compilers\\Nodejs\\app\\node.exe" "D:\\Compilers\\Nodejs\\app\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "node-notifier"
> 15 verbose node v10.5.0
> 16 verbose npm  v6.1.0
> 17 error code E500
> 18 error 500 Internal Server Error: node-notifier@latest
> 19 verbose exit [ 1, true ]

Tried it with the firewall disabled.
Running Windows 10 x64.

**Comment by crazy-max** [comment]
Cannot reproduce your problem :

![image](https://user-images.githubusercontent.com/1951866/42455119-a180ab06-8391-11e8-84f9-2df5a41b72ca.png)

Seems to be an error on the registry. Can you try again ?
