### ISSUE TITLE
[Feature Request]Able to launch with PowerShell instead cmd

### ISSUE THREAD

**Issue by h404bi** [crazy-max/nodejs-portable#40]
Concept:
Add a attribute in `nodejs-portable.conf`, e.g.

``` json
{
  "version": "2.4.0",
  "terminal": "powershell",
  "immediateMode": false,
  "workPath": "./work",
  "customPaths": [
    "C:/Program Files (x86)/Git/cmd",
    "D:/another_path",
    "../a_relative_path"
  ]
}
```

if terminal set to powershell, using powershell while launching, and default set to cmd.

**Comment by Recycling-Bin** [comment]
Need this especially in environments where IT disables CMD but leaves Powershell open 
![image](https://user-images.githubusercontent.com/39171349/47793010-a6e52980-dcf3-11e8-901a-b07c8e1c62b8.png)

**Comment by crazy-max** [comment]
Solved in 2.5.0

**Comment by h404bi** [comment]
It still create and call [`launch.bat`](https://github.com/crazy-max/nodejs-portable/blob/master/app/app/app.go#L115-L136) file which needs cmd, I'm thinking that if it could switch to create `launch.ps1`, to solve @Recycling-Bin 's problem.

**Comment by crazy-max** [comment]
@h404bi Ok thanks I will check this out

**Comment by crazy-max** [comment]
@h404bi No need to convert the script. Only cmd shell is disabled. Not the execution.
