### ISSUE TITLE
Trojan

### ISSUE THREAD

**Issue by automan25** [crazy-max/nodejs-portable#41]
My virus scanner sees nodejs-portable.exe as a trojan virus and deletes it automatically.

**Comment by crazy-max** [comment]
Hi @automan25, it's a false positive. A [common issue with apps written in Golang](https://github.com/crazy-max/WindowsSpyBlocker/wiki/miscFAQ#antivirus-complains-about-windowsspyblocker). I have submitted the app to an antivirus company. I keep you in touch.

**Comment by automan25** [comment]
I figured it was something like that. I look forward to a resolution as I have no control over whitelisting apps on my company computer.

**Comment by crazy-max** [comment]
Ok what is your antivirus btw ?

**Comment by automan25** [comment]
McAfee Endpoint Security

**Comment by UnacceptableUse** [comment]
Also having this issue, was fine until this morning where McCafee decided it didn't like it anymore.

**Comment by crazy-max** [comment]
BitDefender has whitelisted the signature. Wait and see for McAfee

**Comment by crazy-max** [comment]
Seems to be ok now

**Comment by automan25** [comment]
It works for me now as well. Thanks for fixing it. That was quick.

**Comment by nul800sebastiaan** [comment]
☹

BitDefender is still blocking this for me and just trying to download the 2.7.0 release fails as well. I don't know how they whitelist something and then start blocking it again after a while?

**Comment by crazy-max** [comment]
I have sent 2.7.0 to BitDefender. Just wait for them to put it in their whitelist.

**Comment by nul800sebastiaan** [comment]
Aha! I thought that was the one that was submitted before. Thanks for submitting again! What a pain, wish they could make it a bit more clever and do alternate scanning of nodejs-portable in the future.

**Comment by nul800sebastiaan** [comment]
Seems to work again now! 🎉
