### ISSUE TITLE
How to set a proxy ?

### ISSUE THREAD

**Issue by Aymkdn** [crazy-max/nodejs-portable#46]
Hi,

It looks like you added a proxy feature, however you don't explain how to use it... Any direction ? Right now I'm not able to access to it due to proxy issue.

Thanks

**Comment by crazy-max** [comment]
Hi @Aymkdn,

```
npm config set proxy http://proxy.company.com:8080
npm config set https-proxy http://proxy.company.com:8080
```

More info: https://jjasonclark.com/how-to-setup-node-behind-web-proxy/
