### ISSUE TITLE
Location of package installations

### ISSUE THREAD

**Issue by humbienri** [crazy-max/nodejs-portable#48]
Loving this application! And i just started playing with it but I really like the idea of running this off my flash drive and having a mobile NodeJS development environment.  Thank you very much!

However, I am having some issues.  Where are packages installed? I am trying to install pnpm but ended up having to use yarn instead of npm.  npm kept getting hung up on trying to delete a file that was not found. Weird.

With yarn, when I install pnpm I do get a "successful" message but after that not only can I just run pnpm, since said command is not found, but also I've no idea where it is that pnpm was allegedly succesfully installed to?  Please help me.

Thank you @crazy-max! =)

**Comment by crazy-max** [comment]
Hi @humbienri,

Can you give me your install command ?
In my case it works using `npm install -g pnpm` :

![image](https://user-images.githubusercontent.com/1951866/62023797-b89c2480-b1d2-11e9-8b2a-57b0ff3b0c71.png)

`pnpm.bat` is located in `app` folder as it is installed as a global package.

**Comment by humbienri** [comment]
Hello @crazy-max 

Thank you for the quick response! Much appreciated. Below is a screenshot of my prompt:
![NodeJSPortable_2019Jul29100627_ENOENTnosuchfile](https://user-images.githubusercontent.com/1178569/62059485-015ed800-b1e9-11e9-8cea-d63d2c2788a1.png)

Do you think it has anything to do with the fact that I am running off an SD card?  It's not out of space, 20+ Gigs left.

**Comment by crazy-max** [comment]
It looks like npm doesn't have enough permission on your device. Can you try with another one ?

**Comment by humbienri** [comment]
Hello,
Device?  You mean on my SD card, as in try installing it on another drive?  I wonder if running nodejs-portable with Administrative permissions would work?  I don't have another flash drive at the moment; not 'til I get home.

Thank you sir.

**Comment by crazy-max** [comment]
Yes I mean another peripheral like a USB key to check if it's a permission issue. It could be a [write access](https://www.easeus.com/partition-manager-software/change-the-read-write-permission.html) issue.

**Comment by humbienri** [comment]
That would be rather strange since I have no problem writing other files to that folder and/or that device.  But I'll give it a try.

Thanks again @crazy-max!
