### ISSUE TITLE
Portability with DB

### ISSUE THREAD

**Issue by javadevelopment4** [crazy-max/nodejs-portable#61]
It would be great....Node JS made portable with NoSQL DB as well..

Is it possible to bundle both Node JS and Mongo as Portable ???? That would be great

Just for reference: https://github.com/Monglo/MongloDB

- Portable of Node Js, Mongo to be used in Pen drive
- Portable of any OS - Windows/Linux/Mac

So that single bundled zip file or folder can be used in any OS 

Basically wanted to make the full fledged application as Portable.......

**Comment by crazy-max** [comment]
@javadevelopment4,

That is not the purpose of this project. Nevertheless, thank you for your suggestion.

**Comment by javadevelopment4** [comment]
But is there is anything can be done for the request. If yes, it would be really helpful. Please add it if possible. Although the project scope is different.
